### ISSUE TITLE
[feature] Mesos方案支持prometheus ServiceMonitor

### ISSUE THREAD

**Issue by zmberg** [Tencent/bk-bcs#514]
**feature相关背景与描述**
```
apiVersion: monitor.bkbcs.tencent.com/v1
kind: ServiceMonitor
metadata:
  name: your_name
  namespace:  test
  labels:
    app: prometheus-operator-thanos-sidecar
    release: "po" # 必须带这个label
spec:
  selector:
    matchLabels:
      app: po-thanos-sidecar-http
      release: po
  namespaceSelector:
    matchNames:
      - "thanos"
  endpoints:
  - port: http-metrics
    interval: 30s
    params:
      client_id:
      - monitoring
      user_token:
      - xxx
```
