### ISSUE TITLE
[feature] Hook operator add fast Successful Option.

### ISSUE THREAD

**Issue by wenxinlee2015** [Tencent/bk-bcs#766]
**feature相关背景与描述**
hook判定该metric是否成功时，增加满足“成功次数、连续成功次数”的情形，使得gdp、gsts控制器快速进入更新或删除操作，无需等到count数量为止。

**解决方案描述**
在hook template中增加该2个字段，hook-operator进行每次task时，统计该2个字段的值；metric更新状态时参考此字段来更新metric状态。

**其他可行性方案分析**
暂无

**其他补充信息**
暂无

**Comment by wenxinlee2015** [comment]
已开发自测完成，用户接入测试中
template示例：
```yaml
spec:
  metrics:
  - name: webtest
    count: 30
    interval: 10s
    failureLimit: 20
    successfulLimit: 5
    failureCondition: "asInt(result) != 1"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/1
        jsonPath: "{$.id}"
  - name: webtest2
    count: 30
    interval: 10s
    failureLimit: 20
    consecutiveSuccessfulLimit: 2
    failureCondition: "asInt(result) != 2"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/2
        jsonPath: "{$.id}"
```
