### ISSUE TITLE
[feature] port resource pool of cloud loadbalancer

### ISSUE THREAD

**Issue by abstractmj** [Tencent/bk-bcs#957]
# Cloud LoadBalancer Port Pool Proposal

## 1. Motivation

在容器化场景下，特别是云化环境下，游戏PVP服务实例等有状态服务实例通常需要借用云上负载均衡器的能力保证服务的安全性和稳定性，且每个Pod需要对外暴露不同的端口，以供客户端访问。
在已经提供的bcs-ingress-controller方式下，需要提前设计映射规则，在多环境多版本场景下，管理不够便捷直观。

期望有一种更加直观的方案，在不需要提前设定映射规则的情况下，使得单个pod能够绑定云负载均衡器端口资源。该方案需要具有以下功能：

* 维护云负载均衡器端口资源池，能够动态地向资源池中增加和删除云负载均衡器
* Pod通过简单的annotation进行端口资源绑定
* Pod中程序需要读取到绑定的负载均衡器信息和端口信息
* 需要某种机制通知Pod绑定过程是否已完成

## 2. 方案架构

* 采取webhook的方式拦截Pod的创建过程，对存在特定annotation的Pod进行端口的提前分配和注入
* 复用原始bcs-ingress-controller同步能力

### 3.1 端口池定义

```golang
type PortPoolItem struct {
    // 同一个PortPoolItem中的端口会同时生效同一个Pod中
    // 如果在PortPoolItem中新增LB实例，不会对已关联的Pod生效，只会对新增Pod生效
    ItemName        string    `json:"itemName"`
    LoadBalancerIDs []string  `json:"loadBalancerIDs"`
    StartPort       uint32    `json:"startPort"`
    EndPort         uint32    `json:"endPort"`
}

type PortPoolSpec struct {
    PoolItems  []*PortPoolItem  `json:"poolItems"`
    listenerAttribute *IngressListenerAttribute `json:"listenerAttribute,omitempty"`
}

type PortPoolItemStatus struct {
    ItemName              string                 `json:"itemName"`
    PoolItemLoadBalancers []*IngressLoadBalancer `json:"poolItemLoadBalancers"`
    Status                string                 `json:"status"`
}

type PortPoolStatus struct {
    PoolItems []*PortPoolItemStatus `json:"poolItems,omitempty"`
}
```

用户操作的yaml样例

```yaml
apiVersion: networkextension.bkbcs.tencent.com/v1
kind: PortPool
metadata:
  name: portpool-example1
  namespace: default
spec:
  # 在一个资源池中可以动态增删clb资源
  poolItems:
  - name: item1
    loadBalancerIDs: ["ap-shanghai:lb-test1", "lb-test11"]
    startPort: 30000
    endPort: 65000
  - name: item2
    loadBalancerID: ["ap-shenzhen:lb-test2"]
    startPort: 30000
    endPort: 65000
# status部分由BCS自动生成
status:
  poolItems:
  - name: item1
    poolItemLoadBalancers:
    - loadbalancerName: lb-test1-name
      loadBalancerID: lb-test1
      region: ap-shanghai
      type: public
      IPs: ["127.0.0.1"]
    - loadbalancerName: lb-test11-name
      loadBalancerID: lb-test11
      region: ap-shanghai
      type: public
      IPs: ["127.0.0.3"]
    status: Active
  - name: item2
    loadbalancerName: lb-test2-name
      loadBalancerID: lb-test2
      region: ap-shenzhen
      type: public
      IPs: ["127.0.0.2"]
    status: Active
```

### 3.2 Pod资源绑定对象

Pod资源绑定对象名字和ns和Pod一样

```golang
type PortBindingItem struct {
    PoolName string `json:"portPoolName"`
    PoolNamespace string `json:"portPoolNamespace"`
    listenerAttribute *IngressListenerAttribute `json:"listenerAttribute,omitempty"`
    PoolItemLoadBalancers []*IngressLoadBalancer `json:"poolItemLoadBalancers"`
    Ports []int `json:"ports"`
}

type PortBindingSpec struct {
    PortBindingList []*PortBindingItem `json:"portPoolBindList"`
}

type PortBindingStatusItem struct {
    PoolName string `json:"portPoolName"`
    PoolNamespace string `json:"portPoolNamespace"`
    // 单个Pool绑定的状态, NotReady, Binding, Ready, Unbinding
    Status string `json:"status"`
}

type PortBindingStatus struct {
    // 整体Pod绑定的状态, NotReady, PartialReady, Ready
    Status string `json:"status"`
    PortBindingStatusList []*PortBindingStatusItem `json:"portPoolBindStatusList,omitempty"`
}
```

### 3.2 用户使用方式

用户下发的yaml文件

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # 端口来源的端口池，定义的80端口从portpool-example1.testns端口池中分配端口，定义的tcp-test端口从portpool-example2.testns2端口池中分配端口
        # 形式是 {Pool} {protocol} {端口号或者名字}
        #       {Pool} {端口号或者名字}
        portpools.networkextension.bkbcs.tencent.com: |-
            portpool-example1.testns 80
            portpool-example2.testns2 TCP_UDP tcp-test
        # 【可选】是否需要对Pod增加readiness gate，如果增加readiness gate，在clb绑定完成之前，Pod将处于NotReady状态
        readinessgate.portpools.networkextension.bkbcs.tencent.com: "true" 
        # 在容器销魂之后，分配端口的最大保留时间，默认不保留。
        #【注意】：对于无固定名字的Pod，不要设置保留时间，极有可能泄漏
        releasedelay.portpools.networkextension.bkbcs.tencent.com: "22h"
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        - name: tcp-test
          containerPort: 81
```

### 3.3 Pod信息注入与获取

经过webhook注入后

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # 端口来源的端口池，定义的80端口从portpool-example1.testns端口池中分配端口，定义的tcp-test端口从portpool-example2.testns2端口池中分配端口
        # 形式是 {Pool} {protocol} {端口号或者名字}
        #       {Pool} {端口号或者名字}
        portpools.networkextension.bkbcs.tencent.com: |-
            portpool-example1.testns 80
            portpool-example2.testns2 TCP_UDP tcp-test
        # 【可选】是否需要对Pod增加readiness gate，如果增加readiness gate，在clb绑定完成之前，Pod将处于NotReady状态
        readinessgate.portpools.networkextension.bkbcs.tencent.com: "true"
        # 被注入的端口信息
        ports.portpools.networkextension.bkbcs.tencent.com: |-
            [
                {
                    "poolName": "portpool-example1",
                    "poolNamespace": "test-ns1",
                    "portList": [
                        {
                            "lbID": "lb-test1",
                            "vips": ["127.0.0.1"],
                            "vport": 12345,
                            "containerPort": 80,
                            "protocol": "TCP"
                        }
                        {
                            "lbID": "lb-test2",
                            "vips": ["127.0.0.2"],
                            "vport": 12345,
                            "containerPort": 80,
                            "protocol": "TCP"
                        }
                    ]
                },
                {
                    {
                        "poolName": "portpool-example2",
                        "poolNamespace": "test-ns2",
                        "vipList": [
                            {
                                "lbID": "lb-test2",
                                "vips": ["127.0.0.2"],
                                "vport": 12543,
                                "containerPort": 81,
                                "protocol": "TCP_UDP",
                            }
                        ]
                    }
                }
            ]
        # 端口信息状态，当端口被成功绑定之后，此字段将被更新成ready
        status.portpools.networkextension.bkbcs.tencent.com: "binding"
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        - name: tcp-test
          containerPort: 81
        env:
        - name: BCS_PORTPOOL_PORT_80_VIPLIST
          value: "127.0.0.1:12345,127.0.0.3:12345"
        - name: BCS_PORTPOOL_PORT_80_PROTOCOL
          value: "TCP"
        - name: BCS_PORTPOOL_PORT_81_VIPLIST
          value: "127.0.0.2:22222"
          value: BCS_PORTPOOL_PORT_81_PROTOCOL
          value: "TCP_UDP"
    status:
      conditions:
      # 【可选】注入的readiness gate，当端口被成功绑定之后，此Status将被更新成“True”
      - type: "networkextension.bkbcs.tencent.com/portpool"
        status: "False"
        lastProbeTime: null
        lastTransitionTime: 2018-01-01T00:00:00Z
```

**用户程序获取信息**的方式

用户可以将annotations通过downwardAPI挂载成容器内部的卷，当annotations更新时，用户程序可通过文件读取到变化

```yaml
...
     spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
      ...
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
...
```

### 健康检查

* 定期轮训Pool中的clb状态，如果clb状态异常（如被删除），则置为该clb不可分配。同时支持将clb健康检查状态以metric的形式暴露到集群监控中
* 在PortPool创建的时候，提前创建所定义端口段的所有TCP和UDP端口，加速后面Pod IP和clb的绑定过程。
* 对于pod所关联的“端口绑定对象”，增加一个延迟清理时间，在此期间重复创建的Pod能够复用相同的Vip和Vport，延迟时间在Pod级别支持可配。默认不保留。（如果对Deployment的Pod增加）
* 采用metric的方式暴露端口资源池的使用情况，后期需要详细metric指标的说明
* 不同集群不能共用clb，bcs-ingress-controller支持clb实例打tag防止多集群之前的clb使用冲突
