### ISSUE TITLE
[feature] bcs-logbeat-sidecar 支持 multiline 配置，日志采集生命周期优化

### ISSUE THREAD

**Issue by AlexAi27** [Tencent/bk-bcs#962]
### 具体流程
![image](https://user-images.githubusercontent.com/23451421/128820274-0b7956fb-3ff3-4a87-b2d6-3edc71889115.png)

- 当容器触发 `die`, `stop` 事件时，保留日志采集配置，修改配置使采集器读到日志末尾后主动释放日志文件，避免占用fd导致cbs无法解挂，出现Pod无法退出的情况。同时，可以配置最大持续采集时间，当时间到但采集器仍未采集完日志，仍然主动释放日志文件。
- 当容器触发 `destroy` 事件时，删除日志配置，保证日志采集器释放日志文件

### CRD变化

```yaml
spec:
 # in second，容器退出后持续采集时间，如果出现pod terminating因为日志采集卡住则需要配置
  exitedContainerLogCloseTimeout: 10
# multiline 采集配置，详见https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
  multiline:
    type: pattern
    pattern: "^[\\{\\t][\\s\\S]*"
    match: before
    #negate: 
    #flushPattern:
    #maxLines:
    #timeout:
    #countLines:
    #skiplNewline:
# 容器内日志配置
  containerConfs:
  - multiline:
      type: pattern
      pattern: "^[\\{\\t][\\s\\S]*"
      match: before

```
